### ISSUE TITLE
Actual INSERT examples

### ISSUE THREAD

**Issue by afoeder** [dschreck/php-eav-example#1]
Hi,

could you provide, maybe even in the README, just a stack of INSERT statements which will represent how the data is actually stored later in the DB?

What I fand to find out is how you handle the different types, if at all. As far as I see it the actual _values_ of the _attributes_ are stored in `eav_values`.`value_name` (`varchar(50)`) which I find, btw, misleading; value_value would be a better name (or, why prepend `value` anyways since it's the `values` table already.

So, is every "value value" stored as string then? This wouldn't help me in what I was searching for, because I especially needed a solution to tackle different data types to query against them (like in gt and lt etc. operations)...

Thanks and best!

**Comment by dschreck** [comment]
You can change the value type as you need, varchar works as it can handle both text or numerical characters. The naming convention I used is just my personal preference, feel free to edit as you se fit.

The example file pump-data.php will populate your mysql table for the examples, but here's the inserts:
INSERT INTO `eav_entities` VALUES (1,'car_XFV001'),(2,'car_XFV002'),(3,'car_XFV003');
INSERT INTO `cars` VALUES (1,1,1),(1,2,2),(1,3,3),(1,4,4),(1,5,5),(2,1,1),(2,2,7),(2,3,8),(2,4,9),(2,5,5),(3,1,11),(3,2,12);
INSERT INTO `eav_attributes` VALUES (4,'color'),(2,'make'),(3,'model'),(1,'type'),(5,'year');
INSERT INTO `eav_values` VALUES (5,'2011'),(4,'black'),(12,'ferrari'),(9,'grey'),(3,'lancer'),(2,'mitsubishi'),(11,'new'),(1,'used'),(8,'V50'),(7,'volvo');
